variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_HOST_URL: "http://sonarqube:9000"
  # You should set SONAR_TOKEN as a GitLab CI/CD variable for security
#  property "sonar.token", "sqp_b99268d55784add102b34772d3b2cd7cd0c1e6c5"
#  property "sonar.token" , "sqp_927663c06cbab3f4dbe27871abc6a1ae654bf865"
  SONAR_TOKEN: "sqp_927663c06cbab3f4dbe27871abc6a1ae654bf865"

stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
    - ls -l build/libs/
  artifacts:
    paths:
      - build/libs/
      - build/classes/

test:
  stage: test
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  image: gradle:latest
  script:
    - ./gradlew sonarqube -Dsonar.projectKey=fitness-app-backend
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
  dependencies:
    - build
  services:
    - name: sonarqube:latest
      alias: sonarqube
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker-compose up --build -d
  services:
    - name: docker:latest
