variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_PROJECT_KEY: "FitnessApp-Backend2"
  SONAR_PROJECT_NAME: "FitnessApp-Backend2"
  SONAR_HOST_URL: "http://localhost:9000"
  SONAR_TOKEN: "sqp_927663c06cbab3f4dbe27871abc6a1ae654bf865"

stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
    - ls -l build/libs/
  artifacts:
    paths:
      - build/libs/
      - build/classes/

test:
  stage: test
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonarqube -Dsonar.projectKey="$SONAR_PROJECT_KEY" -Dsonar.projectName="$SONAR_PROJECT_NAME" -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.login="$SONAR_TOKEN" -Dsonar.scm.disabled=true
  dependencies:
    - build
  services:
    - name: sonarqube:latest
      alias: sonarqube
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker-compose up --build -d
