variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_PROJECT_KEY: "FitnessApp-Backend2"
  SONAR_PROJECT_NAME: "FitnessApp-Backend2"
  SONAR_HOST_URL: "http://sonarqube:9000"
  SONAR_TOKEN: "sqp_927663c06cbab3f4dbe27871abc6a1ae654bf865"

stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
    - ls -l build/libs/
  artifacts:
    paths:
      - build/libs/
      - build/classes/

test:
  stage: test
  script:
    - ./gradlew test

sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonarqube -Dsonar.projectKey=${FitnessAppBE} -Dsonar.projectName=${FitnessAppBE} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${sqp_5897c86278c0283af11a841841290766cd48a03f} -Dsonar.scm.disabled=true
  dependencies:
    - build
  services:
    - name: sonarqube:latest
      alias: sonarqube
      command: ["-Dsonar.search.javaAdditionalOpts=-Xmx512m", "-Dsonar.web.javaOpts=-Xmx512m"]
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker-compose up --build -d
