version: '3.8'

services:
  fitness-app:
    image: fitness-app-backend:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8090:8080"

    environment:
      JAVA_OPTS: ""

    restart: unless-stopped