version: '3.8'

services:
  fitness-app:
    image: fitness-app-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fitness-app-db:3306/fitness_app_db
    networks:
      - fitness-network
    restart: unless-stopped

  fitness-app-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: fitness_app_db
      MYSQL_ROOT_PASSWORD: FontysPass12#
    ports:
      - "3308:3306"  # Changed from 3307 to 3308
    networks:
      - fitness-network
    restart: unless-stopped

#  sonarqube:
#    image: sonarqube:latest
#    ports:
#      - "9000:9000"
#    networks:
#      - fitness-network
#    environment:
#      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
#    restart: unless-stopped

networks:
  fitness-network:
    driver: bridge
