name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: ./gradlew assemble

      - name: List build artifacts
        run: ls -l build/libs/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/libs/
            build/classes/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: ./gradlew test jacocoTestReport

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

  sonarqube-check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for SonarQube to initialize
        run: sleep 30

      - name: Run SonarQube analysis
        run: |
          ./gradlew sonarqube -Dsonar.coverage.jacoco.xmlReportPaths="build/reports/jacoco/test/jacocoTestReport.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"
        continue-on-error: true

  sonarqube-vulnerability-report:
    runs-on: ubuntu-latest
    needs: sonarqube-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch SonarQube vulnerability report
        run: |
          curl -u "${{ secrets.SONAR_TOKEN }}:" "${{ env.SONAR_HOST_URL }}/api/issues/gitlab_sast_export?projectKey=FitnessApp&branch=${GITHUB_REF_NAME}" -o gl-sast-sonar-report.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"
        continue-on-error: true

      - name: Upload SonarQube vulnerability report
        uses: actions/upload-artifact@v3
        with:
          name: sonar-vulnerability-report
          path: gl-sast-sonar-report.json

  deploy:
    runs-on: ubuntu-latest
    needs: sonarqube-vulnerability-report
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: docker-compose up --build -d
